####################################
# Ziwei Deng                       #
# http://github.com/               #
####################################

# Modified from Ziwei Deng, 
# https://shiny.rstudio.com/gallery/shiny-theme-selector.html

# Concepts about Reactive programming used by Shiny, 
# https://shiny.rstudio.com/articles/reactivity-overview.html

# Load R packages
library(shiny)
library(shinythemes)
# Load reticulate into current R session
library(reticulate)
library(here)
use_python("/Users/zway/Downloads/4100-Capstone/RBERT-Tool/env/bin/python")

# Retrieve/force initialization of Python
reticulate::py_config()

# Check if python is available
reticulate::py_available()

# Install Python package into virtual environment
reticulate::py_install("transformers", pip = TRUE)

# Also installing pytorch just as a contingency?
reticulate::py_install(c("torch", "sentencepiece"), pip = TRUE)


# Importing 🤗 transformers into R session
transformers <- reticulate::import("transformers")

# Instantiate a pipeline for text-classification
classifier <- transformers$pipeline(task = "text-classification", model='distilbert-base-uncased-finetuned-sst-2-english')
# Instantiate a pipeline for question-answering
reader <- transformers$pipeline(task = "question-answering", model='distilbert-base-cased-distilled-squad')

# Load Tidyverse
library(tidyverse)


  # Define UI
ui <- fluidPage(theme = shinytheme("yeti"),
                navbarPage(
                  # theme = "cerulean",  # <--- To use a theme, uncomment this
                  "RBERT Tool",
                  tabPanel("Text Classification",
                           sidebarPanel(
                             tags$h3("Input:"),
                             textInput("txt1", "Paste your text here:", "text"), #txt1 will be sent to server
                             submitButton(text = "Analyse", icon = NULL, width = NULL),
                             
                           ), # sidebarPanel
                           mainPanel(
                             h1("Text Classification"),
                             
                             h3("Output:"),
                             verbatimTextOutput("class"),#txtout will be generated by server
                             
                           ) # mainPanel
                           
                  ), # Navbar 1, tabPanel
                  tabPanel("Question Answering", 
                           sidebarPanel(
                             tags$h3("Input:"),
                             textInput("txt2", "Paste your text here:", "text"), 
                             textInput("question", "Type your question here:", "question"),
                             submitButton(text = "Submit", icon = NULL, width = NULL),
                           ), # sidebarPanel
                           mainPanel(
                             h1("Question Answering"),
                             
                             h3("Answer:"),
                             verbatimTextOutput("answer"),#txtout will be generated by server
                             
                           ) # mainPanel
                           
                  ),# Navbar 2, tabPanel
                  
                ) # navbarPage
) # fluidPage


# Define server function  
server <- function(input, output) {
   
  output$class <- renderPrint({
    input$button
    classifier(input$txt1)
  })
  
  output$answer <- renderPrint({
    input$button
    reader(question = input$question, context = input$txt2)
  })
  
  
} # server


# Create Shiny object
shinyApp(ui = ui, server = server)